trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  jobs:
    - job: dev1
      steps:
      - bash: echo Dev First Job
    - job: Dev2
      steps:
      - bash: echo Dev Second Job
- stage: QA Deploy
  jobs:
    - job: QA Job
      steps:
      - bash: echo QA First Job
- stage: Production Deploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo Production First Job